### ISSUE TITLE
Does Not Register Wine as Installed

### ISSUE THREAD

**Issue by katalia369** [flathub/io.github.sharkwouter.Minigalaxy#4] opened 2020-10-04 16:24 UTC
Wine 5.0.2
Linux Mint 20
Mini Galaxy 0.9.1 Flathub

When I go to preferences and try to kick the slider to allow my Windows game to show it states that I must have Wine installed, which I do. Even after a reboot it is not detecting the Wine. 

Thank You
Mrs. J

**Comment by tim77** [comment] 2020-10-04 20:11
Hi @katalia369. Unfortunately WINE is still not available on Flathub. This is [first step](https://github.com/flathub/flathub/pull/1830) which need to be done and hope we will see it one day packaged. Until then don't even bother with installing WINE on your host via your distro package manager, this will not work.

But working, flatpak'ed WINE you can grab [here](https://github.com/gasinvein/flatpak-apps-staging/tree/org.winehq.Wine/master) and compile it yourself, JFYI.

**Comment by Zlopez** [comment] 2020-12-15 18:31
Could the [community build of Proton](https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Proton) be used for this? At least Steam flatpak is using it for Proton 5.13 right now.

**Comment by tim77** [comment] 2020-12-20 03:34
> Could the community build of Proton be used for this?

Short answer: no.
Long answer: :soon:

**Comment by tim77** [comment] 2021-01-10 20:27
Minigalaxy now reusing Steam Proton extension. Seems work. But keep in mind that this is just temporal solution until standalone or/and reusable Wine and it's derivatives such as Proton will be packaged on Flathub. At this moment `dxvk` and `vkd3d` will not work. Adding them to current build will be a little bit messy, but maybe we try in future.

At current state it is like: something is better then nothing. But very old games and very new games which have native Vulkan support, like Baldurs Gate 3 for example, should work perfectly fine even with this Steam Proton extensions. Please check and share you feedback.

**Comment by Zlopez** [comment] 2021-01-11 19:05
I tried it today with LIMBO and it worked as it should. 

I must say that I can finally enable Windows games in MiniGalaxy flatpak, which is awesome. Thanks for this :+1:

**Comment by Zlopez** [comment] 2021-05-18 18:01
@tim77 Could you help me with adding `dxvk` and `vkd3d` to minigalaxy flatpak?

**Comment by tim77** [comment] 2021-05-22 15:43
@Zlopez please try Minigalaxy from `beta` branch https://github.com/flathub/io.github.sharkwouter.Minigalaxy/tree/beta#install-dxvk

```sh
flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak install flathub-beta io.github.sharkwouter.Minigalaxy
```

To install DXVK from Beta branch run this commands

```sh
flatpak run --command=sh io.github.sharkwouter.Minigalaxy//beta
winetricks dxvk
exit
```

and then run

```sh
flatpak run io.github.sharkwouter.Minigalaxy//beta
```

**Comment by Zlopez** [comment] 2021-05-24 08:57
I switched to beta today and I'm not sure it works as it should.
I tried to run Etherlords 2, which is platinum on [ProtonDB](https://www.protondb.com/app/270790) and got this:
```
Failed to start Etherlords 2:
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0024:err:winediag:load_dxvk_config Couldn't load dxvk_config.dll, won't apply default DXVK config options
0084:err:rpc:I_RpcReceive we got fault packet with status 0x1c010003
```

**Comment by Zlopez** [comment] 2021-05-27 17:14
I was able to run Etherlords 2 today.
Here is how I was able to do it:
1. I entered the container directly
`flatpak run --command=sh io.github.sharkwouter.Minigalaxy//beta`

2. Went to the game folder
`cd "GOG Games/Etherlords 2"`

3. Run it with wine
`wine Etherlords2.exe`

I tried the same with `wine64` and I got the same output as from the GUI. So I think the GUI is running 64bit wine instead of 32bit  version.

**Comment by tim77** [comment] 2021-05-27 17:34
@Zlopez good to know. If Minigalaxy running directly via `wine64` i believe this Minigalaxy issue and we should try to fix this somehow upstream...

**Comment by Zlopez** [comment] 2021-05-27 20:38
Let me know if I could help

**Comment by tim77** [comment] 2021-05-27 20:48
We still trying figure out and find best way to package Wine for Flathub (btw check this [thread](https://discourse.flathub.org/t/wine-flathub-meta/986) if you interesting too). This is also one of the reason why messing with current Proton extension is not the best idea, but i hope something is better then nothing. Maybe @sharkwouter also can look into [this](https://github.com/flathub/io.github.sharkwouter.Minigalaxy/issues/4#issuecomment-849801632) since this looks something like should been fixed on Minigalaxy side.

**Comment by Zlopez** [comment] 2021-05-27 21:01
Thanks for the link @tim77. In past there was a flatpak repository called [winepak](https://www.winepak.org/), they created a windows applications packaged with wine. But having wine runtime would be awesome.

**Comment by Zlopez** [comment] 2021-05-28 00:58
I played the Etherlords 2 a little and it seems that the issue is probably more complex. The game was working fine till I got to combat. Upon entering combat my screen started flickering and the game was unplayable. I looked at the logs and saw this:
```
00e0:err:d3d:wined3d_debug_callback 0x2030b8: "GL_INVALID_OPERATION in glDrawArrays(vertex buffers are mapped)".                                                                                                                              
00e0:err:d3d:wined3d_debug_callback 0x2030b8: "GL_INVALID_ENUM in glDisable(GL_FRAGMENT_PROGRAM_ARB)".
00e0:err:d3d:wined3d_debug_callback 0x2030b8: "GL_INVALID_ENUM in glDisable(GL_VERTEX_PROGRAM_ARB)".
00e0:err:d3d:wined3d_debug_callback 0x2030b8: "GL_INVALID_ENUM in glIsEnabled(GL_FRAGMENT_PROGRAM_ARB)".
00e0:err:d3d:wined3d_debug_callback 0x2030b8: "GL_INVALID_ENUM in glDisable(GL_FRAGMENT_PROGRAM_ARB)".
00e0:err:d3d:wined3d_debug_callback 0x2030b8: "GL_INVALID_ENUM in glIsEnabled(GL_VERTEX_PROGRAM_ARB)".
00e0:err:d3d:wined3d_debug_callback 0x2030b8: "GL_INVALID_ENUM in glDisable(GL_VERTEX_PROGRAM_ARB)".
00e0:err:d3d:wined3d_debug_callback 0x2030b8: "GL_INVALID_ENUM in glDisable(GL_FRAGMENT_PROGRAM_ARB)".
00e0:err:d3d:wined3d_debug_callback 0x2030b8: "GL_INVALID_ENUM in glDisable(GL_VERTEX_PROGRAM_ARB)".
```
This was repeated over and over again. It looks like the DXVK is not used at all and the game is using wined3d instead. 
I also found this when the game is starting:
```
esync: up and running.                                                                                                                                                                                                                        
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely                                                                                                                                                                                  
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION                                                                                                                                                           
0024:fixme:ddraw:DirectDrawEnumerateExA flags 0x00000004 not handled                                                                                                                                                                          
0024:err:winediag:load_dxvk_config Couldn't load dxvk_config.dll, won't apply default DXVK config options                                                                                                                                     
0024:fixme:ddraw:ddraw7_Initialize Ignoring guid {aeb2cdd4-6e41-43ea-941c-8361cc760781}.                                                                                                                                                      
0024:fixme:ddraw:ddraw7_Initialize Ignoring guid {aeb2cdd4-6e41-43ea-941c-8361cc760781}.                                                                                                                                                      
0104:fixme:d3d:surface_cpu_blt Filter WINED3D_TEXF_LINEAR not supported in software blit.                                                                                                                                                     
```
So it looks like it tries to load dxvk_config.dll, but fails and switch to wined3d instead.

I also noticed that the `winetricks dxvk` alerts me that only WINEPREFIX 64bit is available, which should be correct, but could be the issue here (I would say that the Proton on Steam is by default creating 32 bit prefixes for games.). I'm missing the wine 32bit libraries and I'm not sure if it's possible to install them inside flatpak.

**Comment by sharkwouter** [comment] 2021-05-28 06:54
Minigalaxy actually uses the ``wine`` command, not ``wine64``. It doesn't really care where the executable is, it just looks in the path.

**Comment by Zlopez** [comment] 2021-05-28 11:30
@sharkwouter In this case, I'm not sure why Etherlords 2 are not running from GUI, but running fine when started directly in flatpak container.

**Comment by Zlopez** [comment] 2021-05-28 11:44
Maybe I found out the issue. It looks like the issue in case of Etherlords 2 is [here](https://github.com/sharkwouter/minigalaxy/blob/master/minigalaxy/launcher.py#L106), because the first `.exe` file you get by this is config.exe, which just runs the configuration. It would be nice if this could be configured.

**Comment by Eonfge** [comment] 2021-11-18 20:14
I love the Flathub version, if only because it prevents a bloody swarm of gog-related.desktop files from littering my Home-directory.

**Comment by tim77** [comment] 2022-03-27 16:50
Hello everyone. Please test Minigalaxy + Wine Flathub native build in [beta](https://github.com/flathub/io.github.sharkwouter.Minigalaxy/tree/beta#minigalaxy-dev-version) branch. WARNING: old Proton prefixes will not work with Wine.

**Closed** 2022-03-30 16:15 UTC
Labels: enhancement, good first issue
